name = "a11y-book-router"
main = "router-worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "bookshelf.dev/a11y-book", zone_name = "bookshelf.dev" },
  { pattern = "bookshelf.dev/a11y-book/*", zone_name = "bookshelf.dev" },
]
